import type { PageLoad } from './$types';
const welcomeMessages = [
	'Welkom',
	'Mirëseerdhët',
	'እንኳን ደህና መጣህ',
	'مرحبا',
	'ողջույն',
	'xoş',
	'Ongi etorri',
	'жаданы',
	'স্বাগত',
	'Dobrodošli',
	'Добре дошли',
	'Benvinguda',
	'歡迎',
	'Benvenuti',
	'Dobrodošli',
	'Vítejte',
	'Velkommen',
	'Welkom',
	'Welcome',
	'Bonvenon',
	'Teretulnud',
	'Maligayang pagdating',
	'Tervetuloa',
	'Bienvenue',
	'Wolkom',
	'Benvido',
	'კეთილი',
	'Willkommen',
	'καλωσόρισμα',
	'સ્વાગત',
	'Akeyi',
	'Barka',
	'ברוך הבא',
	'स्वागत',
	'Zoo siab txais tos',
	'Üdvözöljük',
	'Velkomin',
	'Namasté',
	'Selamat datang',
	'Fáilte',
	'Benvenuto',
	'ようこそ',
	'ಸ್ವಾಗತ',
	'Қош келдіңіздер',
	'សូមស្វាគមន៍',
	'환영',
	'Bixêrhatin',
	'Cаламдашуу',
	'ຍິນດີຕ້ອນຮັບ',
	'Gratissimum',
	'Esi gaidīts',
	'Sveiki atvykę',
	'Wëllkomm',
	'Добредојдовте',
	'Selamat datang',
	'സ്വാഗതം',
	'Merħba',
	'Nau mai',
	'आपले स्वागत आहे',
	'тавтай морилно уу',
	'ကြိုဆိုပါတယ်',
	'स्वागत',
	'Velkommen',
	'ښه راغلاست',
	'خوش آمد',
	'Witaj',
	'Bem-vindo',
	'ਸੁਆਗਤ ਹੈ',
	'Bun venit',
	'добро пожаловать',
	'Taliga',
	'Fàilte',
	'добродошао',
	'Amohelehile',
	'Kugashira',
	'ڀلي ڪري آيا',
	'ඔබ සාදරයෙන් පිළිගනිමු',
	'Vitajte',
	'Dobrodošli',
	'Bienvenido',
	'Wilujeung sumping',
	'Karibu',
	'Välkommen',
	'Хуш омадед',
	'வரவேற்கிறோம்',
	'స్వాగతం',
	'ยินดีต้อนรับ',
	'Hoşgeldin',
	'Ласкаво просимо',
	'آمدید',
	'Xush kelibsiz',
	'Chào mừng bạn',
	'Croeso',
	'באַגריסן',
	'Siyakwamukela'
];

export const load: PageLoad = () => {
	return {
		welcomeMessage: welcomeMessages[Math.floor(Math.random() * welcomeMessages.length)]
	};
};
