export const codes = {
	impala: 'Impossible Error (31)',
	robert: 'WriteCopy changed (30)',
	moded: 'Stealth Edit Revival (29)',
	booing: 'Tried to modify hash function (28)',
	bobby: 'Function Return Check Failed (27)',
	vera: 'Tried to get build tools (26)',
	vegah: 'VEH used (25)',
	fisher: 'HumanoidState::computeEvent changed (24)',
	dallas: 'DLL Injection (23)',
	tomy: 'Sandbox or VM detected (22)',
	usain: 'Speedhack. (21)',
	carol: 'Lua vm hooked (20)',
	steven: 'OSX hash changed (19)',
	larry: 'Our VEH hook removed (18)',
	mal: 'Any New CE Method (17)',
	ebx: 'HumanoidState::computeEvent changed ebx (16)',
	terrance: 'Early null weak pointer (15)',
	ursula: 'Lua hash changed (14)',
	bruger: 'Speculative Call Check (13)',
	seth: 'SEH chain into dll (12)',
	curly: 'Hooked API function (11)',
	olivia: 'Debugger found (10)',
	norman: 'Lua script hash changed (9)',
	mallory: 'Catch executable acccess violation (8)',
	lance: 'Const Changed (7)',
	jack: 'Invalid bytecode (6)',
	imogen: 'Memory hash changed (5)',
	ivan: 'Illegal scripts (4)',
	omar: 'Bad signature (3)',
	moe: 'detected HWBP (2)',
	lafayette: 'xxhash broken (1)',
	murdle: 'Cheat Engine Stable Methods (0)',
	suzanne: 'Debugger found (10)',
	richard: 'Speedhack. (21)',
	mcc: 'MCC',
	ghector: 'SecurityException',
	Guardian: 'NetPmc Pending P7.',
	hector: 'MemHashError',
	jesper: 'invalid number of hashes',
	Nyx: 'Range has been modified',
	WorldEdit: 'NetPmc Error P2.',
	Zek: 'SecurityException',
	Zix: 'SecurityException',
	Zot: 'Api Token Tamper',
	baseball: 'Hash Mismatch',
	unknown: 'Unknown Error'
}

export const codesZod = [
	'impala',
	'robert',
	'moded',
	'booing',
	'bobby',
	'vera',
	'vegah',
	'fisher',
	'dallas',
	'tomy',
	'usain',
	'carol',
	'steven',
	'larry',
	'mal',
	'ebx',
	'terrance',
	'ursula',
	'bruger',
	'seth',
	'curly',
	'olivia',
	'norman',
	'mallory',
	'lance',
	'jack',
	'imogen',
	'ivan',
	'omar',
	'moe',
	'lafayette',
	'murdle',
	'suzanne',
	'richard',
	'mcc',
	'ghector',
	'Guardian',
	'hector',
	'jesper',
	'Nyx',
	'WorldEdit',
	'Zek',
	'Zix',
	'Zot',
	'baseball',
	'unknown'
] as const
